version: "3.3"

services:
    elasticsearch:
        image: elasticsearch:6.8.8
        restart: always
        hostname: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: "-Xms512m -Xmx512m" 
            network.host: 0.0.0.0
        volumes:
            - ./es-data1:/usr/share/elasticsearch/data
        networks:
            - bridge
        logging:
            options:
                max-size: "1m"
                max-file: "2"
            driver: json-file
    kibana:
        image: kibana:6.8.13
        restart: always
        hostname: kibana
        ports:
            - 5601:5601
        networks:
            - bridge
        logging:
            options:
                max-size: "1m"
                max-file: "2"
            driver: json-file

networks:
    bridge:
        driver: bridge
